baseurl = "https://gizmolab.net/"
defaultContentLanguage = "el"
languageCode = "el-gr"
theme = "terminal"
paginate = 5
paginatePath = ""
copyright = "🄯 copyleft 2024 gizmo_lab"
title = "gizmo_lab"
timeZone = "Europe/Athens"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  keywords = "hacklab, free software, foss, open source, thessaloniki"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  emptySectionMessage = "Δυστυχώς δεν υπάρχει κάτι μέχρι στιγμής :("

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true
  
  # set a custom cover (default is the favicon)
  customCover = "gizmolab-cover.png"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "gizmolab-favicon.ico"
  
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  oneHeadingSize = false

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[languages]
  [languages.el]
    languageName = "Ελληνικά"
    subtitle = "Το gizmolab είναι ένα hack-lab στην Θεσσαλονίκη"
    menuMore = "Περισσότερα"
    readMore = "Διάβασε περισσότερα"
    readOtherPosts = "Άλλες δημοσιεύσεις"
    newerPosts = "Νεότερες δημοσιεύσεις"
    olderPosts = "Παλαιότερες δημοσιεύσεις"
    missingContentMessage = "Η σελίδα δε βρέθηκε..."
    missingBackButtonLabel = "Πίσω στην αρχική σελίδα"

    [languages.el.params.logo]
      logoImg = "/gizmolab-logo-small.png"
      logoText = "Gizmolab"
      logoHomeLink = "/"

    [languages.el.menu]
      [[languages.el.menu.main]]
        identifier = "actions"
        name = "Δράσεις"
        url = "/actions"
        weight = 2
      [[languages.el.menu.main]]
        identifier = "ekdiloseis"
        name = "Εκδηλώσεις"
        url = "/events"
        weight = 3
      [[languages.el.menu.main]]
        identifier = "about"
        name = "Σχετικά"
        url = "/about"
        weight = 4
      [[languages.el.menu.main]]
        identifier = "contact"
        name = "Επικοινωνία"
        url = "/contact"
        weight = 5 
       [[languages.el.menu.main]]
        identifier = "wiki"
        name = "Wiki"
        url = "https://wiki.gizmolab.net/"
        weight = 6 
