backend:
  name: github
  repo: g1zmolab/website
  branch: main

media_folder: "assets/images"
public_folder: "/images"

local_backend: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

locale: 'gr'

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Δημοσιεύσεις"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug_url}}" #todo: try to add greeklish slug
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Τιτλος", name: "title", widget: "string"}
      - {label: "ημερομηνια δημοσιευσης", name: "date", widget: "datetime"}
      - {label: "Slug για το URL (η ημερομηνια μπαινει αυτοματα)", name: "slug_url", widget: "string"}
      - {label: "ετικετες", name: "tags", widget: "list"}
      - {label: "κειμενο", name: "body", widget: "markdown"}

  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Εκδηλώσεις"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug_url}}" #todo: try to add greeklish slug
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Τιτλος", name: "title", widget: "string"}
      - {label: "ημερομηνια δημοσιευσης", name: "date", widget: "datetime"}
      - {label: "ημερομηνια καλεσματος", name: "event_date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss"}
      - {label: "Slug για το URL (η ημερομηνια μπαινει αυτοματα)", name: "slug_url", widget: "string"}
      - {label: "εικονα", name: "thumbnail", widget: "image", choose_url: true, required: false}
      - {label: "ετικετες", name: "tags", widget: "list"}
      - {label: "κειμενο", name: "body", widget: "markdown"}

  - name: "actions" # Used in routes, e.g., /admin/collections/blog
    label: "Δράσεις"
    folder: "content/actions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug_url}}" #todo: try to add greeklish slug
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Τιτλος", name: "title", widget: "string"}
      - {label: "ημερομηνια δημοσιευσης", name: "date", widget: "datetime"}
      - {label: "ημερομηνια καλεσματος", name: "event_date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss"}
      - {label: "Slug για το URL (η ημερομηνια μπαινει αυτοματα)", name: "slug_url", widget: "string"}
      - {label: "εικονα", name: "thumbnail", widget: "image", choose_url: true, required: false}
      - {label: "ετικετες", name: "tags", widget: "list"}
      - {label: "κειμενο", name: "body", widget: "markdown"}

  - label: "Σελίδες"
    name: "pages"
    files:
      - label: "Σχετικά"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Επικοινωνία"
        name: "contact"
        file: "content/contact.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Επόμενη συνέλευση"
        name: "next-assembly"
        file: "data/next_assembly.yml"
        fields:
          - label: "Date"
            name: "date"
            widget: "datetime"
            date_format: "DD/MM/YYYY" # e.g. 24.12.2021
            time_format: "HH:mm" # e.g. 21:07
            format: "YYYY-MM-DDTHH:mm:ss"
